/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DTOCSThread */

#ifndef _Included_DTOCSThread
#define _Included_DTOCSThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DTOCSThread
 * Method:    DTOCS_cpp
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_DTOCSThread_DTOCS_1cpp
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
